project:
  type: website
  output-dir: docs

website:
  title: "<strong>Marino</strong> Lab"

  navbar:
    left:
      - text: Home
        href: index.qmd

      - text: Research
        href: research.qmd

      - text: People
        href: people.qmd

      - text: Publications
        href: publications.qmd

      - text: Collaborative Network
        href: collaborators.qmd

      - text: Events & Conferences
        href: where2meet.qmd
        
      - text: Join us!
        href: join.qmd

  page-footer:
    center:
      <div class="custom-footer">

        <div class="footer-section">
          <i class="fas fa-graduation-cap"></i>
          <a href="https://scholar.google.com/citations?user=WoJoj4MAAAAJ&hl=en/" target="_blank">Google Scholar</a>
        </div>

        <div class="footer-section">
          <i class="fas fa-flask"></i>
          <a href="https://www.researchgate.net/profile/Emanuele-Marino?ev=hdr_xprf" target="_blank">ResearchGate</a>
        </div>

        <div class="footer-section">
          <i class="fab fa-linkedin"></i>
          <a href="https://www.linkedin.com/in/emanuele-marino-2b91b888/" target="_blank">LinkedIn</a>
        </div>

        <div class="footer-section footer-copy">
          <i class="far fa-copyright"></i>
          <span>2026 Emanuele Marino</span>
        </div>

      </div>
      
format:
  html:
    theme: superhero
    css: 
      - styles.css
      - collaborators.css
    anchor-sections: false
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">