---
title: "Join Us!"
---

Currently, we do not have open positions. **However**, we are always interested in hearing from motivated students and postdoctoral researchers who are keen to pursue their research in our group. Prospective applicants are strongly encouraged to get in touch well in advance of the relevant deadline to allow for sufficient time to prepare a competitive proposal.

**Prospective students:** Students interested in pursuing a PhD in our group are encouraged to apply through the departmental PhD programme. The call for applications typically opens in early July and closes in early August, with positions starting in early November. More information can be found on the official call page [here](https://www.unipa.it/dipartimenti/difc/dottorati/scienzefisicheechimiche/bando.html).

**Prospective postdoctoral candidates:** We welcome inquiries from postdoctoral candidates seeking external funding opportunities. We are happy to support applications for competitive fellowships, including the Marie Skłodowska-Curie Postdoctoral Fellowships. More information about the MSCA programme can be found [here](https://marie-sklodowska-curie-actions.ec.europa.eu/actions/postdoctoral-fellowships).

## How we work

Research in our lab is highly **hands-on and interdisciplinary**.

Students are trained in the wet synthesis of colloidal nanoparticles, as well as their purification, assembly, and structural and optical characterization. They also learn to design and build functional platforms such as microfluidic chips.

This experimental work is complemented by opportunities to explore molecular dynamics simulations of nanoparticle assembly and simulations of light--matter interactions.

Students are encouraged to take ownership of their projects early on, while receiving close guidance and training from the PI.

## Lab culture

We aim to maintain a **collaborative and supportive environment** in which ideas are shared openly and students help each other across projects.

The PI is actively involved in training and supervision, but students are encouraged from an early stage to develop independence and ownership of their research.

## Is this lab a good fit for you?

This lab may be a good fit if you:

- enjoy hands-on experimental work;
- like building things and seeing tangible outcomes;
- are excited by open-ended problems with many parameters to explore;
- are interested in working at the interface of physics, chemistry, and engineering.

It may be less ideal if you are looking for a highly structured project with fixed outcomes or for a purely theoretical environment.

## Joining the lab

If you are interested in joining the lab, feel free to get in touch. A good way to start the conversation is to mention which of the research directions above you find most interesting, and why.